# Generated by Django 5.2.1 on 2025-05-21 17:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speech',
            options={'ordering': ['-upload_date']},
        ),
        migrations.RemoveField(
            model_name='speech',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='speech',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='speech',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='speech',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speech',
            name='processing_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speech',
            name='processing_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speech',
            name='upload_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='speech',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='speech',
            name='transcript',
            field=models.TextField(blank=True, null=True),
        ),
    ]
