# Generated by Django 5.2.1 on 2025-05-21 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_speech_options_remove_speech_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeechAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure_score', models.IntegerField(blank=True, null=True)),
                ('argument_score', models.IntegerField(blank=True, null=True)),
                ('persuasiveness_score', models.IntegerField(blank=True, null=True)),
                ('rhetoric_score', models.IntegerField(blank=True, null=True)),
                ('delivery_score', models.IntegerField(blank=True, null=True)),
                ('feedback', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('speech', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='core.speech')),
            ],
            options={
                'verbose_name_plural': 'Speech analyses',
            },
        ),
    ]
